# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNHereMapsIos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  platform :ios, '12.0'

  # Pods for RNHereMapsIos
  pod 'HEREMaps', '>= 3.14'

end
